---
# vars file for ansible-netplan
netplan_enabled: true
netplan_config_file: /etc/netplan/ansible-netplan.yaml
netplan_renderer: networkd
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: no
        addresses:
        - "{{ ansible_default_ipv4.address }}/24"
        gateway4: "{{ ansible_default_ipv4.address.split('.')[:-1] | join('.') }}.1"
        nameservers:
          addresses: [8.8.8.8]