---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
    - role: hostname
    - role: ansible-netplan

- hosts: master
  become: yes
  any_errors_fatal: true
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node
