---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  any_errors_fatal: true
  roles:
    - role: ansible-netplan
    - role: k3s/master

- hosts: node
  become: yes
  tasks:
  - debug: var=ansible_default_ipv4.address
  roles:
  - role: ansible-netplan
  - role: k3s/node
